apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-grpc
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50