apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: d-api-rest-grpc
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: d-api-rest-grpc
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50