apiVersion: v1
kind: Service
metadata:
  name: d-api-rest-grpc-service
  namespace: project
spec:
  selector:
    app: d-api-rest-grpc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP