apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis
  namespace: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50