apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  namespace: project
spec:
  selector:
    matchLabels:
      app: grpc
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc-server
        image: allenrovas/grcp_server_pr2:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        ports:
          - containerPort: 3001
        env:
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_USER
        - name: DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_NAME
      - name: grpc-client
        image: allenrovas/grcp_client_pr2:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        ports:
          - containerPort: 3000
        env:
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_USER
        - name: DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-go
              key: DB_NAME
      imagePullSecrets:
        - name: dockerhubpull