apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: project # Cambia el namespace si es necesario
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg== # "mongoadmin" en base64
  mongo-root-password: cGFzc3dvcmQxMjM= # "password123" en base64
  mongo-database: bXlkYg== # "mydb" en base64