[package]
name = "redis_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
redis = { version = "0.26", features = ["aio", "tokio-comp"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }